DRAFT. GHActions DTS-Server rollout

diff --git a/.github/workflows/deploy-action.yml b/.github/workflows/deploy-action.yml
--- a/.github/workflows/deploy-action.yml
+++ b/.github/workflows/deploy-action.yml
@@ -1,5 +1,5 @@
 name: Terraform and Deploy on DTS
-# DRAFT. GHActions DTS-Server rollout 
+# DRAFT. GHActions DTS-Server rollout
 on:
   push:
     branches:
@@ -24,21 +24,21 @@ jobs:
     - name: Terraform Init
       run: terraform init
 
-    # # Step 4: Extract server IP using Terraform output
-    # - name: Extract Server IP
-    #   id: get_ip
-    #   run: |
-    #     server_ip=$(terraform output -raw server_ip_tf || echo "ERROR") # Default to "ERROR" if command fails
-    #     if [ "$server_ip" = "ERROR" ]; then
-    #       echo "Error extracting server IP" 
-    #       exit 1
-    #     fi
-    #     echo "Extracted server IP: $server_ip" # Debug statement
-    #     echo "SERVER_IP=$server_ip" >> $GITHUB_ENV
+    # Step 4: Extract server IP using Terraform output
+    - name: Extract Server IP
+      id: get_ip
+      run: |
+        server_ip=$(terraform output -raw server_ip_tf || echo "ERROR") # Default to "ERROR" if command fails
+        if [ "$server_ip" = "ERROR" ]; then
+          echo "Error extracting server IP" 
+          exit 1
+        fi
+        echo "Extracted server IP: $server_ip" # Debug statement
+        echo "SERVER_IP=$server_ip" >> $GITHUB_ENV
 
-    # # Debug environment variable
-    # - name: Debug Environment Variables
-    #   run: cat $GITHUB_ENV
+    # Debug environment variable
+    - name: Debug Environment Variables
+      run: cat $GITHUB_ENV
 
     # # Step 5: Set up SSH with the private key
     # - name: Set up SSH
